CREATE DATABASE nerdgirl_db;
USE nerdgirl_db;
CREATE TABLE nerdgirls(
id INT AUTO_INCREMENT NOT NULL,
nerdgirl_name VARCHAR(50) NOT NULL,
occupation VARCHAR(50),
linkedin_url VARCHAR(3000),
PRIMARY KEY(id)
);

CREATE DATABASE user_db;
USE user_db;
CREATE TABLE users(
id INT AUTO_INCREMENT NOT NULL,
user_name VARCHAR(50) NOT NULL,
post VARCHAR(20000),
PRIMARY KEY(id)
);